title = "Grid Theme"
theme = "grid-theme-hugo"
paginate = 5
pygmentsStyle = "solarized-dark" # solarized-light, -dark or -dark256
copyright = ""

relativeURLs = true

[params]
  scheme = "dark" # light, dark, gray or preference
  description = "Reporting Live"

[menu]
  [[menu.main]]
    name = "Feed"
    url = "/index.xml"
  [[menu.main]]
    name = "About"
    url = "https://github.com/glalonde/"